<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
  <div class="checkout-success">
    <div class="thanks-success">
        <div class="thanks-img"><img class="success-img" src="http://local.medizinhub.com/media/wysiwyg/tick.png" alt=""></div>
        <p class="order-confirmed">Your Order is Confirmed!</p>
        <p class="shipping-order">We’ll send you a order to your shipping address
    as soon as possible</p>
    <div class="primary">
                <button class="button-success"><a class="btn-success"
                  href="<?= $block->escapeUrl($block->getContinueUrl()) ?>">Continue Shopping</a></button>
            </div>
    </div>
    </div>
